---
# Implement your Workload deployment tasks here

- name: Setting up halkyon
  debug:
    msg: "Setting up halkyon"

- name: Install heml tool
  include_tasks:
    file: ./helm.yml

- name: Deploy Tekton pipelines
  include_tasks:
    file: ./tekton.yml

- name: Install KubeDB Operator
  include_tasks:
    file: ./kubedb.yml

- name: Deploy Component Operator
  include_tasks:
    file: ./operator.yml

- name: Grant cluster sudoer role to users
  shell: |
    oc --kubeconfig={{ kube_config }} adm policy add-cluster-role-to-user sudoer {{ item }}
  with_items:
  - admin
  - user1
  - user2

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
