- name: Remove SnowDrop web site k8s resources
  command: {{ client_tool }} {{ k8s_config }} delete -f https://raw.githubusercontent.com/snowdrop/snowdrop-site-angular/master/openshift/snowdrop-site.yaml
