- name: Stop cluster
  command: oc cluster down
  register: clusterupout

- name: Cluster down
  include_tasks: cluster_down.yml

- name: Show cluster up output
  debug:
    var: clusterupout.stdout_lines