---
- hosts: circleci
  gather_facts: True

  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  # Define default values for variables that are common between roles
  vars:
    client_tool: kubectl

  roles:
    - { role: '../../ansible/playbook/roles/k8s_cluster',             tags: 'k8s_cluster'}
    - { role: '../../ansible/playbook/roles/k8s_config',              tags: 'k8s_config'}
    - { role: '../../ansible/playbook/roles/kubedb',                  tags: 'kubedb'}
    - { role: '../../ansible/playbook/roles/k8s_service_broker',      tags: 'k8s_service_broker'}
    - { role: '../../ansible/playbook/roles/docker_registry',         tags: 'docker_registry'}
    - { role: '../../ansible/playbook/roles/tekton_pipelines',        tags: 'tekton_pipelines'}
    - { role: '../../ansible/playbook/roles/component_crd_operator',  tags: 'component_crd_operator'}
    - { role: '../../ansible/playbook/roles/ocp4_console',            tags: 'ocp4_console'}
 -m
