- name: Copy bash files to /var/lib/origin directory
  copy:
    src: "{{ item }}"
    dest: "/var/lib/origin/{{ item | basename }}"
  with_fileglob:
    - "files/*.sh"

- name: Copy systemctl okd.service file to /etc/systemd/system
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | basename }}"
  with_fileglob:
    - "files/*.service"

- name: Register okd.service to make it available when VM boots
  systemd:
    name: okd.service
    enabled: yes
    daemon_reload: yes
  register: start_result


