- name: Find the Linux asset 
  set_fact:
    asset_url: "{{ item.browser_download_url }}"
    asset_name: "{{ item.browser_download_url | basename }}"
  when: "'linux-64bit' in item.name and 'server' in item.name"

