- name: Uninstall Tekton Pipelines on Openshift
  shell: |
    {{ client_tool }} {{ openshift_env.oc_admin_kubeconfig_arg }} delete -f https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager.version }}/cert-manager.yaml
  when: isOpenshift | bool

- name: Uninstall Cert Manager on K8s
  shell: |
    {{ client_tool }} delete -f https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager.version }}/cert-manager.yaml
  when: not isOpenshift | bool
