---
- hosts: masters
  gather_facts: True

  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  # Define default values for variables that are common between roles
  vars:
    client_tool: kubectl

  roles:
    - { role: 'k8s_cluster',   tags: 'create_cluster'}
    - { role: 'docker_registry',   tags: 'docker_registry'}
    - { role: 'tekton_pipelines',   tags: 'tekton_pipelines'}
    - { role: 'component_crd_operator',  tags: 'component_crd_operator'}
