---
# Required variables:
#  . vm_name: Name of the vm
#  . pass_provider: provider in the passstore project [hetzner]
#  . k8s_type: Kubernetes host type [masters,nodes], empty for no k8s installation
#  . k8s_version: Kubernetes version [115,116], empty for no k8s installation
- name: "Generate inventory files on the controller"
  hosts: localhost
  gather_facts: no

  pre_tasks:
    - name: "Validate required variables"
      assert:
        that:
          - "vm_name is defined"
          - "pass_provider is defined"
          - "k8s_type is defined"
          - "k8s_version is defined"
        fail_msg: 
          - "Required parameters:"
          - "  vm_name: Name of the vm"
          - "  pass_provider: provider in the passstore project [hetzner]"
          - "  k8s_type: Kubernetes host type [masters,nodes], empty for no k8s installation"
          - "  k8s_version: Kubernetes version [115,116], empty for no k8s installation"

    - name: "Pull pass git database"
      shell: "git pull"
      args:
        chdir: "{{ lookup('env', 'PASSWORD_STORE_DIR') }}"

    - name: Check k8s_type value
      fail:
        msg: "Invalid k8s type {{ k8s_type }}. Should be in [masters,nodes]"
      when: "k8s_type != 'masters' and k8s_type != 'nodes' and k8s_type | length > 0"
      tags: [always]

    - name: Check k8s_version value
      fail:
        msg: "Invalid k8s version {{ k8s_version }}. Should be in [117 ... 121]"
      when: "k8s_version != '117' and k8s_version != '118' and k8s_version != '119' and k8s_version != '120' k8s_version != '121' and k8s_version | length > 0"
      tags: [always]

  tasks:
    - name: "Execute create inventory, if tagged as so"
      include_role:
        name: "passstore/ansible_inventory"
        apply:
          tags:
            - always
      vars:
        pass_l1: "{{ pass_db_name | default('snowdrop') }}"
        pass_l2: "{{ pass_provider | default('hetzner') }}"
        pass_l3: "{{ vm_name }}"
        operation: "create"
      tags: [never,create]

    - name: "Build inventory"
      include_role:
        name: "passstore/ansible_inventory"
        apply:
          tags:
            - always
      vars:
        pass_l1: "{{ pass_db_name | default('snowdrop') }}"
        pass_l2: "{{ pass_provider | default('hetzner') }}"
        pass_l3: "{{ vm_name }}"
      tags: [always]

    - name: "Add to k8s version"
      include_role:
        name: "passstore/ansible_inventory"
        tasks_from: "add_variable"
        apply:
          tags:
            - always
      vars:
        pass_l1: "snowdrop"
        pass_l2: "{{ pass_provider }}"
        pass_l3: "{{ vm_name }}/groups/"
        var_name: "{{ item }}"
        var_value: "."
      loop:
        - "{{ k8s_type }}"
        - "k8s_{{ k8s_version }}"
      when: "k8s_type is defined and k8s_type | length > 0 and k8s_version is defined and k8s_version | length > 0"
      tags: [always]

  post_tasks:
    - name: "Push changes to the pass git database"
      shell: "git push"
      args:
        chdir: "{{ lookup('env', 'PASSWORD_STORE_DIR') }}"
...
