---
- name: Update docker config
  include: docker_config.yml

- name: Disable selinux
  include_tasks: selinux.yml

- name: Check if oc binary exists
  stat:
    path: "{{ openshift_client_dest }}/oc" 
  register: oc_client

- name: Get the client assets 
  include_tasks: get_client_assets.yml

- name: Install the oc binary client
  include_tasks: install_oc_client.yml
  when: not oc_client.stat.exists or openshift_force_client_install
  
- name: Check if running
  include_tasks: isrunning.yml

- name: Config to start the all in one Openshift cluster using command 'oc cluster up'
  debug:
    msg: "Parameters : {{ openshift_up_options }}"

- name: Run oc cluster up
  command: "oc cluster up {{ openshift_up_options }}"
  register: clusterupout
  ignore_errors: yes

- name: Cluster up
  include_tasks: cluster_up.yml

- name: Give cluster-admin to developer
  include_tasks: grant_admin.yml

- name: Create a symbolic link between folders of OpenShift and /etc/origin as this one is used by the openshift ansible playbook to access master.yml config file
  command: ln -s /var/lib/openshift/config/ /etc/origin

- name: Show cluster up output
  debug:
    var: clusterupout.stdout_lines
