- name: Check if master config is already patched
  command: cat {{ openshift_env.config_dir }}/kube-apiserver/master-config.yaml
  register: master_content

- block:
  - name: Stop okd service
    systemd:
      state: stopped
      name: okd.service

  - name: Generate patch using template
    template:
      src: "mutating_webhook_patch.j2"
      dest: /tmp/mutating_webhook_patch.json

  - name: Get patch file
    command: cat /tmp/mutating_webhook_patch.json
    register: patch

  - name: Patch master-config file to use Mutating Webhook
    command: "oc ex config patch {{ openshift_env.config_dir }}/kube-apiserver/master-config.yaml --patch='{{ patch.stdout }}'"
    register: r

  - name: Display master-config.yml file before to patch it
    debug:
      msg: "Before to patch: {{ master_content.stdout }}"

  - name: Copy patch to new master config file
    copy: content="{{ r.stdout }}" dest={{ openshift_env.config_dir }}/kube-apiserver/master-config.yaml

  - name: Display master-config.yml patched
    debug:
      msg: "After we patch it: {{ r.stdout }}"

  - name: Restart okd service
    systemd:
      state: restarted
      name: okd.service
  when: master_content.stdout.find('MutatingAdmissionWebhook') == -1
