- name: Create internal mount directory
  shell: |
    mkdir -p /tmp/{{ item.key }}
    chmod -R 777 /tmp/{{ item.key }}
    chmod -R a+w /tmp/{{ item.key }}
  with_dict: "{{ volumes }}"

- name: Copy pv file to master
  template:
    src: "{{ role_path }}/files/pv.yml.j2"
    dest: "/tmp/{{ item.key }}.yml"
  with_dict: "{{ volumes }}"
