# Change within the `configMap` of the Broker, the field `auto_escalate` to true otherwise, the Broker's pod will report this error `Unable to retrieve cluster roles rules from cluster`
---
apiVersion: v1
kind: Namespace
metadata:
  name: automation-broker-apb

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: automation-broker-apb
  namespace: automation-broker-apb

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: automation-broker-apb
roleRef:
  name: cluster-admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: automation-broker-apb
    namespace: automation-broker-apb

---
apiVersion: batch/v1
kind: Job
metadata:
  name: automation-broker-apb
  namespace: automation-broker-apb
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccount: automation-broker-apb
      containers:
        - name: apb
          image: docker.io/automationbroker/automation-broker-apb:latest
          args:
            - "provision"
            - "-e create_broker_namespace=true"
            - "-e broker_auto_escalate=true"
            - "-e wait_for_broker=true"
          imagePullPolicy: IfNotPresent
