launcher_project_name: devex

# Please provide your username/token as openshift parameter
launcher_github_username:
launcher_github_token:

# For local usage, you can use this address : http://launcher-keycloak:8080/auth
launcher_keycloak_url:
# For local usage, you can use this realm : launch
launcher_keycloak_realm:

# Check these values as they could be different for your cluster
launcher_openshift_user: admin
launcher_openshift_pwd: admin

launcher_template_version: master
launcher_template_name: fabric8-launcher
launcher_template_url: https://raw.githubusercontent.com/fabric8-launcher/launcher-openshift-templates/{{ launcher_template_version }}/openshift/launcher-template.yaml

launcher_catalog_git_repo: https://github.com/fabric8-launcher/launcher-booster-catalog.git
launcher_catalog_git_branch: master

launcher_openshift_console_url: https://192.168.99.50:8443/

launcher_keycloak_template_name: launcher-keycloak
launcher_catalog_filter: 