---
- name: "Install core kubernetes modules"
  hosts: "{{ override_host | default('masters') }}"
  gather_facts: "{{ gathering_host_info | default('true') | bool == true }}"

  # Define default values for variables that are common between roles
  vars:
    client_tool: kubectl

  roles:
    - role: 'k8s_cluster'
      tags: [always,k8s_cluster]
    - role: 'k8s_config'
      tags: [always,k8s_config]
    - role: 'ingress'
      tags: [always,ingress]
    - role: 'k8s_dashboard'
      tags: [k8s_dashboard]
