---
- name: Converge
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: "Set godaddy facts"
      ansible.builtin.set_fact:
        api_key: "{{ query('passwordstore', 'godaddy/ote/api-key')[0] }}"
        api_secret: "{{ query('passwordstore', 'godaddy/ote/secret-key')[0] }}"

  tasks:
    - name: "Include domain"
      ansible.builtin.include_role:
        name: "domain"

...
