---
- name: Make temp directory for files
  command: mktemp -d /tmp/ansible-XXXXXX
  register: mktemp
  changed_when: False

- name: Copy files to temp directory
  copy:
    src: "{{ item }}"
    dest: "{{ mktemp.stdout }}/{{ item | basename }}"
  with_fileglob:
  - "files/*.yml"

- name: Generate Operator file
  template:
    src: operator.j2
    dest: /tmp/operator.yml

- name: Generate Cluster RBAC file
  template:
    src: cluster-rbac.j2
    dest: /tmp/cluster-rbac.yml

- name: Create Openshift project for the component operator
  command: "{{ client_tool }} new-project {{ component_operator_namespace }}"
  ignore_errors: true
  when: isOpenshift | bool

- name: Create Kubernetes namespace for the component operator
  command: "{{ client_tool }} create namespace {{ component_operator_namespace }}"
  ignore_errors: true
  when: not isOpenshift | bool

- name: Install serviceaccount, customresourcedefinition resources (static files from mktemp dir)
  command: |
    {{ client_tool }} apply -f "{{ mktemp.stdout }}" -n {{ component_operator_namespace }}

- name: Install rbac, operator
  shell: |
    {{ client_tool }} apply -f /tmp/cluster-rbac.yml -n {{ component_operator_namespace }}
    {{ client_tool }} apply -f /tmp/operator.yml -n {{ component_operator_namespace }}

- name: Wait for the Component CRD to be created
  command: "{{ client_tool }} get crd components.devexp.runtime.redhat.com"
  register: crd
  until: crd.rc == 0
  delay: 5
  retries: 5
