- name: Check if project/namespace exists
  command: oc get project/{{ launcher_project_name }} -n {{ launcher_project_name }}
  register: r_get_project
  ignore_errors: true

- name: Create project if it doesn't exist yet
  command: oc new-project {{ launcher_project_name }}
  when: r_get_project.stdout == ""

- name: Check if Launcher template exists
  command: oc get template/{{ launcher_template_name }} -n {{ launcher_project_name }}
  register: r_get_template
  ignore_errors: true

- name: Deploy the Launcher template
  command: oc create -n {{ launcher_project_name }} -f https://raw.githubusercontent.com/fabric8-launcher/launcher-openshift-templates/{{ launcher_template_version }}/openshift/launcher-template.yaml
  when: r_get_template.stdout == ""

- name: Display parameters to create launcher app
  debug:
    msg:
      - "Template Url : {{ launcher_template_url }}"
      - "Parameters used to create the application from the template : "
      - "LAUNCHER_BOOSTER_CATALOG_REPOSITORY={{ launcher_catalog_git_repo }}"
      - "LAUNCHER_BOOSTER_CATALOG_REF={{ launcher_catalog_git_branch }}"
      - "LAUNCHER_KEYCLOAK_URL={{ launcher_keycloak_url }}"
      - "LAUNCHER_KEYCLOAK_REALM={{ launcher_keycloak_realm }}"
      - "LAUNCHER_MISSIONCONTROL_OPENSHIFT_USERNAME={{ launcher_openshift_user }}"
      - "LAUNCHER_MISSIONCONTROL_OPENSHIFT_PASSWORD={{ launcher_openshift_pwd }}"
      - "LAUNCHER_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL={{ launcher_openshift_console_url }}"
      - "LAUNCHER_MISSIONCONTROL_OPENSHIFT_API_URL={{ launcher_openshift_console_url }}"
      - "LAUNCHER_MISSIONCONTROL_GITHUB_USERNAME={{ launcher_github_username }}"
      - "LAUNCHER_MISSIONCONTROL_GITHUB_TOKEN={{ launcher_github_token }}"

- name: Create launcher application
  shell: |
    oc new-app {{ launcher_template_name }}  -n {{ launcher_project_name }} \
        -p LAUNCHER_BOOSTER_CATALOG_REPOSITORY={{ launcher_catalog_git_repo }} \
        -p LAUNCHER_BOOSTER_CATALOG_REF={{ launcher_catalog_git_branch }} \
        -p LAUNCHER_KEYCLOAK_URL={{ launcher_keycloak_url }} \
        -p LAUNCHER_KEYCLOAK_REALM={{ launcher_keycloak_realm }} \
        -p LAUNCHER_MISSIONCONTROL_OPENSHIFT_USERNAME={{ launcher_openshift_user }} \
        -p LAUNCHER_MISSIONCONTROL_OPENSHIFT_PASSWORD={{ launcher_openshift_pwd }} \
        -p LAUNCHER_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL={{ launcher_openshift_console_url }} \
        -p LAUNCHER_MISSIONCONTROL_OPENSHIFT_API_URL={{ launcher_openshift_console_url }} \
        -p LAUNCHER_MISSIONCONTROL_GITHUB_USERNAME={{ launcher_github_username }} \
        -p LAUNCHER_MISSIONCONTROL_GITHUB_TOKEN={{ launcher_github_token }}
