---
# Origin git hub Repo
openshift_github_user: openshift
openshift_github_name: origin
openshift_github_url: https://api.github.com/repos

# Openshift parameters
openshift_release_tag_name: "v3.10.0"

openshift_client_dest: /usr/local/bin
openshift_force_client_install: false

openshift_recreate: yes

# Cluster configuration
cluster_ip_address: "{{ public_ip_address }}" # Re use the inventory ip address
cluster_use_existing_config: true
cluster_log_level: 1

openshift_up_options: '
  --enable=[automation-service-broker, centos-imagestreams, persistent-volumes, registry, rhel-imagestreams, router, service-catalog, template-service-broker, web-console]
  --write-config=true
  --public-hostname={{ cluster_ip_address }}
  --routing-suffix={{ cluster_ip_address }}.nip.io
  --server-loglevel={{ cluster_log_level }}'

