---
- name: Add default ssh port in host var file
  lineinfile:
    path: "{{ inventory_relative_path }}/host_vars/{{ host_name }}"
    regexp: "^ansible_ssh_port"
    line: "ansible_ssh_port: {{ new_ssh_port_number | default('47286') }}"

- name: Comment the custom ssh port in host var file
  replace:
    path: "{{ inventory_relative_path }}/host_vars/{{ host_name }}"
    regexp: "^new_ssh_port_number"
    replace: "#new_ssh_port_number"

...