---
- name: "Print required information"
  debug: 
    msg:
      - "vm_name: {{ vm_name }}"

- include_tasks: vm_create.yml
  when: "state == 'present'"

- include_tasks: vm_remove.yml
  when: "state == 'absent'"
...