- name: Delete Project {{ item }} if it exists
  shell: oc delete project {{ item }} --ignore-not-found=true --force --now
  with_items:
    - "{{ infra_project }}"

- pause:
    seconds: 30

- name: Create projects
  shell: oc new-project {{ item }}
  with_items:
    - "{{ infra_project }}"